---
- name: "Inatall Apache2 Web Server"
  become: true
  apt:
    name: ["apache2"]
    state: present
    update_cache: yes

- name: "Default index.html file"
  become: true
  copy:
    src: index.html
    dest: /var/www/html/index.html
    backup: yes