AWSTemplateFormatVersion: 2010-09-09
Description: create simple EC2 instance with new Security Group

Parameters:
  EnvironmentName:
    Description: Project Name to be used in names and resources tags
    Type: String

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-052efd3df9dad4825' 
      InstanceType: t2.micro
      Tags: 
          - Key: project
            Value: !Ref EnvironmentName
          - Key: Name
            Value: !Sub  ec2-${EnvironmentName}

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0
      Tags: 
          - Key: project
            Value: !Ref EnvironmentName