version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy Environement
          command: |
            EnvironmentName="udacity-${CIRCLE_WORKFLOW_ID}"
            aws cloudformation delete-stack --stack-name myStack-$EnvironmentName

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: |
            EnvironmentName="udacity-${CIRCLE_WORKFLOW_ID}"
            aws cloudformation deploy \
              --template-file ./cloudformation/ec2_create.yml \
              --stack-name myStack-$EnvironmentName \
              --parameter-overrides EnvironmentName=$EnvironmentName \
              --region us-east-1

  create_inventory_file:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: | 
            yum install -y openssh-client ca-certificates tar gzip git curl wget
      - run:
          command: | 
            echo "[node-web]" > ./ansible-playbook/inventory
            ec2TagValue="ec2-udacity-${CIRCLE_WORKFLOW_ID}"
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].publicDnsName' \
              --filters "Name=tag:Name,Values=$ec2TagValue" \
              --output text >> ./ansible-playbook/inventory
              cat ./ansible-playbook/inventory
      - persist_to_workspace:
          root: ./ansible-playbook/
          paths:
            - inventory

  configure_infrastructure:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1d:c2:25:0f:6d:98:c7:f9:6c:2b:bd:93:0a:45:a5:40"
      - run:
          command: |
            pip install ansible
      - attach_workspace:
          at: ./ansible-playbook/
      - run:
          command: |
            cd ./ansible-playbook
            cat inventory
            ansible-playbook -i inventory remote_node_web.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - attach_workspace:
          at: ./ansible-playbook/
      - run: apk add --update curl git openssh-client gzip tar
      - run:
          name: smoke test
          command: |
            URL=$(grep "amazonaws" ./ansible-playbook/inventory)
            pwd
            ls
            echo $URL
            # Test if website exists
            if curl -s --head ${URL}:3000
            then
              return 0
            else
              return 1
            fi
      - destroy_environment:
          when: on_fail
workflows:
  create-deploy-infrastructure-cicd:
    jobs:
      - create_infrastructure
      - create_inventory_file:
          requires:
            - create_infrastructure
      - configure_infrastructure:
          requires:
            - create_inventory_file
      - smoke_test:
          requires:
            - configure_infrastructure