version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: |
            pwd
            ls
            EnvironmentName="udacity-${CIRCLE_WORKFLOW_ID}"
            aws cloudformation deploy \
              --template-file ec2_create.yml \
              --stack-name myStack-$EnvironmentName \
              --parameter-overrides EnvironmentName=$EnvironmentName
              --region us-east-1

  create_inventory_file:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: | 
            mkdir ~/ansible-inventory
            ec2TagValue="ec2-udacity-${CIRCLE_WORKFLOW_ID}"
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Name,Values=$ec2TagValue" \
              --output text >> ~/ansible-inventory/inventory
      - persist_to_workspace:
          root: ~/ansible-inventory
          paths:
            - inventory 
  deploy_web_app:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: | 
            mkdir ~/ansible-inventory
      - attach_workspace:
          at: ~/ansible-inventory
      - run:
          command: |
            cat inventory

workflows:
  say-hello:
    jobs:
      - create_infrastructure
      - create_inventory_file:
          requires:
            - create_infrastructure
      - deploy_web_app:
          requires:
            - create_inventory_file